// examples/example-vite-svelte-recs/src/App.svelte
<script lang="ts">
    import type { Entity } from "@dojoengine/recs";
    import {
        componentValueStore,
        type ComponentStore,
    } from "./dojo/componentValueStore";
    import { dojo, account, burners } from "./stores";
    import { Account } from "starknet";
    import { type Burner } from "@dojoengine/create-burner";
    import {
        handleBurnerChange,
        handleNewBurner,
        handleClearBurners,
    } from "./handlers";

    let position: ComponentStore;
    let moves: ComponentStore;

    const { clientComponents, torii, burnerManager, client } = $dojo;

    const signer = $account;

    if (signer && torii) {
        const entityId = torii.poseidonHash([signer!.address]) as Entity;
        position = componentValueStore(clientComponents.Position, entityId);
        moves = componentValueStore(clientComponents.Moves, entityId);
    }

</script>

<main>
    {#if $dojo}
        <p>Setup completed</p>
    {:else}
        <p>Setting up...</p>
    {/if}

    <button on:click={handleNewBurner}>
        {burnerManager?.isDeploying ? "deploying burner" : "create burner"}
    </button>

    <div class="card">
        <div>{`burners deployed: ${$burners.length}`}</div>
        <div>
            select signer:{" "}
            <select on:change={handleBurnerChange}>
                {#each $burners as burner}
                    <option value={burner.address}>
                        {burner.address}
                    </option>
                {/each}
            </select>
        </div>
        <div>
            <button on:click={handleClearBurners}> Clear burners </button>
        </div>
    </div>

    <div class="card">
        <button on:click={() => client.actions.spawn({ account: signer! })}>Spawn</button
        >
        <div>
            Moves Left: {moves ? `${$moves?.remaining}` : "Need to Spawn"}
        </div>
        <div>
            Position:{" "}
            {position
                ? `${$position?.vec.x}, ${$position?.vec.y}`
                : "Need to Spawn"}
        </div>

        <div>{$moves && $moves.last_direction}</div>
    </div>

    <div class="card">
        <div>
            <button
                on:click={() =>
                    position && $position.vec.y > 0
                        ? client.actions.move({
                              account: signer!,
                              direction: { type: "Up" },
                          })
                        : console.log("Reach the borders of the world.")}
            >
                Move Up
            </button>
        </div>
        <div>
            <button
                on:click={() =>
                    position && $position.vec.x > 0
                        ? client.actions.move({
                              account: signer!,
                              direction: { type: "Left" },
                          })
                        : console.log("Reach the borders of the world.")}
            >
                Move Left
            </button>
            <button
                on:click={() =>
                    client.actions.move({
                        account: signer!,
                        direction: { type: "Right" },
                    })}
            >
                Move Right
            </button>
        </div>
        <div>
            <button
                on:click={() =>
                    client.actions.move({
                        account: signer!,
                        direction: { type: "Down" },
                    })}
            >
                Move Down
            </button>
        </div>
    </div>
</main>

// examples/react/react-pwa-app/src/App.tsx
import { useComponentValue } from "@dojoengine/react";
import { Entity } from "@dojoengine/recs";
import { useEffect, useState } from "react";
import { Direction } from "./utils";
import { getEntityIdFromKeys } from "@dojoengine/utils";
import { useDojo } from "./dojo/useDojo";
import { AccountInterface } from "starknet";
import "./App.css";

function App() {
    const {
        setup: {
            systemCalls: { spawn, move },
            clientComponents: { Position, Moves },
        },
        burnerManager,
    } = useDojo();

    const [clipboardStatus, setClipboardStatus] = useState({
        message: "",
        isError: false,
    });

    const [account, setAccount] = useState<AccountInterface | null>(null);
    const [entityId, setEntityId] = useState<Entity | undefined>(undefined);

    const position = useComponentValue(Position, entityId);
    const moves = useComponentValue(Moves, entityId);

    useEffect(() => {
        setAccount(burnerManager?.account);
    }, [burnerManager?.account]);

    useEffect(() => {
        if (account) {
            const newEntityId = getEntityIdFromKeys([
                BigInt(account.address),
            ]) as Entity;
            setEntityId(newEntityId);
        } else {
            setEntityId(undefined);
        }
    }, [account]);

    const handleRestoreBurners = async () => {
        try {
            await burnerManager?.applyFromClipboard();
            setClipboardStatus({
                message: "Burners restored successfully!",
                isError: false,
            });
        } catch (error) {
            setClipboardStatus({
                message: `Failed to restore burners from clipboard`,
                isError: true,
            });
        }
    };

    useEffect(() => {
        if (clipboardStatus.message) {
            const timer = setTimeout(() => {
                setClipboardStatus({ message: "", isError: false });
            }, 3000);

            return () => clearTimeout(timer);
        }
    }, [clipboardStatus.message]);

    return (
        <>
            <button onClick={() => burnerManager?.create()}>
                {burnerManager?.isDeploying
                    ? "deploying burner"
                    : "create burner"}
            </button>
            {burnerManager && burnerManager?.list().length > 0 && (
                <button
                    onClick={async () => await burnerManager?.copyToClipboard()}
                >
                    Save Burners to Clipboard
                </button>
            )}
            <button onClick={handleRestoreBurners}>
                Restore Burners from Clipboard
            </button>
            {clipboardStatus.message && (
                <div className={clipboardStatus.isError ? "error" : "success"}>
                    {clipboardStatus.message}
                </div>
            )}

            <div className="card">
                <div>{`burners deployed: ${burnerManager.count}`}</div>
                <div>
                    select signer:{" "}
                    <select
                        value={
                            burnerManager?.account
                                ? burnerManager.account.address
                                : ""
                        }
                        onChange={(e) => burnerManager.select(e.target.value)}
                    >
                        {burnerManager?.list().map((account, index) => {
                            return (
                                <option value={account.address} key={index}>
                                    {account.address}
                                </option>
                            );
                        })}
                    </select>
                </div>
                <div>
                    <button onClick={() => burnerManager.clear()}>
                        Clear burners
                    </button>
                </div>
            </div>

            {account && (
                <>
                    <p>
                        You will need to Authorise the contracts before you can
                        use a burner. See readme.
                    </p>
                    <div className="card">
                        <button onClick={() => spawn(account)}>Spawn</button>
                        <div>
                            Moves Left:{" "}
                            {moves ? `${moves.remaining}` : "Need to Spawn"}
                        </div>
                        <div>
                            Position:{" "}
                            {position
                                ? `${position.vec.x}, ${position.vec.y}`
                                : "Need to Spawn"}
                        </div>

                        <div>{moves && moves.last_direction}</div>
                    </div>

                    <div className="card">
                        <div>
                            <button
                                onClick={() =>
                                    position && position.vec.y > 0
                                        ? move(account, Direction.Up)
                                        : console.log(
                                              "Reach the borders of the world."
                                          )
                                }
                            >
                                Move Up
                            </button>
                        </div>
                        <div>
                            <button
                                onClick={() =>
                                    position && position.vec.x > 0
                                        ? move(account, Direction.Left)
                                        : console.log(
                                              "Reach the borders of the world."
                                          )
                                }
                            >
                                Move Left
                            </button>
                            <button
                                onClick={() => move(account, Direction.Right)}
                            >
                                Move Right
                            </button>
                        </div>
                        <div>
                            <button
                                onClick={() => move(account, Direction.Down)}
                            >
                                Move Down
                            </button>
                        </div>
                    </div>
                </>
            )}
        </>
    );
}

export default App;
