// example/frameworks/svelte/src/App.svelte
<script lang="ts">
import type { Entity } from "@dojoengine/recs";
import { getEntityIdFromKeys } from "@dojoengine/utils";
import { DirectionValue } from "@showcase/dojo";

import {
    componentValueStore,
    type ComponentStore,
} from "./dojo/componentValueStore";
import {
    handleBurnerChange,
    handleClearBurners,
    handleNewBurner,
} from "./dojo/handlers";
import { accountStore, burnerStore, dojoStore } from "./dojo/stores";

let entityId: Entity | undefined;
let positionStore: ComponentStore | undefined;
let movesStore: ComponentStore | undefined;
let clipboardMessage = "";
let clipboardError = false;

$: setup = $dojoStore;
$: account = $accountStore;
$: burners = $burnerStore;

$: if (account) {
    entityId = getEntityIdFromKeys([BigInt(account.address)]) as Entity;
} else {
    entityId = undefined;
}

$: if (setup && entityId) {
    positionStore = componentValueStore(
        setup.clientComponents.Position,
        entityId
    );
    movesStore = componentValueStore(setup.clientComponents.Moves, entityId);
} else {
    positionStore = undefined;
    movesStore = undefined;
}

function showMessage(message: string, isError = false) {
    clipboardMessage = message;
    clipboardError = isError;
    setTimeout(() => {
        clipboardMessage = "";
        clipboardError = false;
    }, 2500);
}

async function copyBurners() {
    if (!setup) return;
    await setup.burnerManager.copyToClipboard();
    showMessage("Burners copied to clipboard");
}

async function restoreBurners() {
    if (!setup) return;
    try {
        await setup.burnerManager.applyFromClipboard();
        burnerStore.set(setup.burnerManager.list());
        accountStore.set(setup.burnerManager.getActiveAccount());
        showMessage("Burners restored");
    } catch (error) {
        console.error(error);
        showMessage("Failed to restore burners", true);
    }
}
</script>

<main>
    {#if !setup}
        <p>Connecting to dojo…</p>
    {:else}
        <section>
            <button on:click={handleNewBurner}>
                {setup.burnerManager.isDeploying
                    ? "Deploying burner"
                    : "Create burner"}
            </button>
            {#if burners.length > 0}
                <button on:click={copyBurners}>Save burners to clipboard</button>
            {/if}
            <button on:click={restoreBurners}>Restore burners from clipboard</button>
            {#if clipboardMessage}
                <p class="feedback" class:error={clipboardError}>
                    {clipboardMessage}
                </p>
            {/if}
        </section>

        <section>
            <p>{`Burners deployed: ${burners.length}`}</p>
            <label class="select">
                <span>Select signer</span>
                <select on:change={handleBurnerChange}>
                    {#each burners as burner}
                        <option
                            value={burner.address}
                            selected={account && burner.address === account.address}
                        >
                            {burner.address}
                        </option>
                    {/each}
                </select>
            </label>
            <button on:click={handleClearBurners}>Clear burners</button>
        </section>

        <section>
            <button
                on:click={() =>
                    account && setup.systemCalls.spawn(account)
                }
            >
                Spawn
            </button>
            <p>
                Moves left:
                {#if movesStore}
                    {$movesStore?.remaining}
                {:else}
                    Need to spawn
                {/if}
            </p>
            <p>
                Position:
                {#if positionStore}
                    {$positionStore?.vec.x}, {$positionStore?.vec.y}
                {:else}
                    Need to spawn
                {/if}
            </p>
        </section>

        <section>
            <button
                on:click={() =>
                    account && positionStore && $positionStore?.vec.y > 0
                        ? setup.systemCalls.move(account, DirectionValue.Up())
                        : null
                }
            >
                Up
            </button>
            <div class="row">
                <button
                    on:click={() =>
                        account && positionStore && $positionStore?.vec.x > 0
                            ? setup.systemCalls.move(account, DirectionValue.Left())
                            : null
                    }
                >
                    Left
                </button>
                <button
                    on:click={() =>
                        account && setup.systemCalls.move(account, DirectionValue.Right())
                    }
                >
                    Right
                </button>
            </div>
            <button
                on:click={() =>
                    account && setup.systemCalls.move(account, DirectionValue.Down())
                }
            >
                Down
            </button>
        </section>
    {/if}
</main>

// example/frameworks/vue/src/App.vue
<template>
    <main>
        <section v-if="loading">
            <p>Connecting to dojo…</p>
        </section>
        <template v-else>
            <section>
                <button @click="createBurner">
                    {{ deploying ? "Deploying burner" : "Create burner" }}
                </button>
                <button v-if="burners.length" @click="copyBurners">
                    Save burners to clipboard
                </button>
                <button @click="restoreBurners">Restore burners from clipboard</button>
                <p v-if="clipboardMessage" :class="['feedback', { error: clipboardError }]">
                    {{ clipboardMessage }}
                </p>
            </section>

            <section>
                <p>Burners deployed: {{ burners.length }}</p>
                <label class="select">
                    <span>Select signer</span>
                    <select :value="activeAccount?.address" @change="selectBurner">
                        <option v-for="burner in burners" :key="burner.address" :value="burner.address">
                            {{ burner.address }}
                        </option>
                    </select>
                </label>
                <button @click="clearBurners">Clear burners</button>
            </section>

            <section>
                <button @click="spawn">Spawn</button>
                <p>
                    Moves left:
                    <span v-if="moves">{{ moves.remaining }}</span>
                    <span v-else>Need to spawn</span>
                </p>
                <p>
                    Position:
                    <span v-if="position">{{ position.vec.x }}, {{ position.vec.y }}</span>
                    <span v-else>Need to spawn</span>
                </p>
            </section>

            <section>
                <button @click="moveUp">Up</button>
                <div class="row">
                    <button @click="moveLeft">Left</button>
                    <button @click="moveRight">Right</button>
                </div>
                <button @click="moveDown">Down</button>
            </section>
        </template>
    </main>
</template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount, reactive, ref, watchEffect } from "vue";
import type { ComponentValue, Entity } from "@dojoengine/recs";
import { getComponentValue } from "@dojoengine/recs";
import { getEntityIdFromKeys } from "@dojoengine/utils";
import type { Burner } from "@dojoengine/create-burner";
import type { Account } from "starknet";

import { DirectionValue, dojoConfig, setup, type SetupResult } from "@showcase/dojo";
import type { Direction } from "@showcase/dojo";

const loading = ref(true);
const deploying = ref(false);
const setupResult = ref<SetupResult | null>(null);
const burners = ref<Burner[]>([]);
const activeAccount = ref<Account | null>(null);
const clipboardMessage = ref("");
const clipboardError = ref(false);
const position = ref<ComponentValue<any> | null>(null);
const moves = ref<ComponentValue<any> | null>(null);

let positionSubscription: { unsubscribe: () => void } | null = null;
let movesSubscription: { unsubscribe: () => void } | null = null;

function resetSubscriptions() {
    positionSubscription?.unsubscribe();
    positionSubscription = null;
    movesSubscription?.unsubscribe();
    movesSubscription = null;
}

function showMessage(message: string, isError = false) {
    clipboardMessage.value = message;
    clipboardError.value = isError;
    window.setTimeout(() => {
        clipboardMessage.value = "";
        clipboardError.value = false;
    }, 2500);
}

async function initialise() {
    const result = await setup(dojoConfig);
    setupResult.value = result;
    burners.value = result.burnerManager.list();
    activeAccount.value =
        result.burnerManager.getActiveAccount() ?? result.masterAccount;
    loading.value = false;
}

function entityId(): Entity | null {
    if (!activeAccount.value) return null;
    return getEntityIdFromKeys([BigInt(activeAccount.value.address)]) as Entity;
}

function selectBurner(event: Event) {
    if (!setupResult.value) return;
    const target = event.target as HTMLSelectElement;
    setupResult.value.burnerManager.select(target.value);
    activeAccount.value = setupResult.value.burnerManager.getActiveAccount();
    burners.value = setupResult.value.burnerManager.list();
}

async function createBurner() {
    if (!setupResult.value) return;
    deploying.value = true;
    await setupResult.value.burnerManager.create();
    burners.value = setupResult.value.burnerManager.list();
    activeAccount.value = setupResult.value.burnerManager.getActiveAccount();
    deploying.value = false;
}

function clearBurners() {
    if (!setupResult.value) return;
    setupResult.value.burnerManager.clear();
    burners.value = setupResult.value.burnerManager.list();
    activeAccount.value = null;
}

async function copyBurners() {
    if (!setupResult.value) return;
    await setupResult.value.burnerManager.copyToClipboard();
    showMessage("Burners copied to clipboard");
}

async function restoreBurners() {
    if (!setupResult.value) return;
    try {
        await setupResult.value.burnerManager.applyFromClipboard();
        burners.value = setupResult.value.burnerManager.list();
        activeAccount.value = setupResult.value.burnerManager.getActiveAccount();
        showMessage("Burners restored");
    } catch (error) {
        console.error(error);
        showMessage("Failed to restore burners", true);
    }
}

async function spawn() {
    if (!setupResult.value || !activeAccount.value) return;
    await setupResult.value.systemCalls.spawn(activeAccount.value);
}

function move(direction: Direction) {
    if (!setupResult.value || !activeAccount.value) return;
    setupResult.value.systemCalls.move(activeAccount.value, direction);
}

function moveUp() {
    if (position.value && position.value.vec.y > 0) {
        move(DirectionValue.Up());
    }
}

function moveDown() {
    move(DirectionValue.Down());
}

function moveLeft() {
    if (position.value && position.value.vec.x > 0) {
        move(DirectionValue.Left());
    }
}

function moveRight() {
    move(DirectionValue.Right());
}

watchEffect(() => {
    resetSubscriptions();

    if (!setupResult.value || !activeAccount.value) {
        position.value = null;
        moves.value = null;
        return;
    }

    const id = entityId();
    if (!id) return;

    const { clientComponents } = setupResult.value;

    position.value = getComponentValue(clientComponents.Position, id);
    moves.value = getComponentValue(clientComponents.Moves, id);

    positionSubscription = clientComponents.Position.update$.subscribe(
        (update) => {
            if (update.entity === id) {
                const [next] = update.value;
                position.value = next as typeof position.value;
            }
        }
    );

    movesSubscription = clientComponents.Moves.update$.subscribe((update) => {
        if (update.entity === id) {
            const [next] = update.value;
            moves.value = next as typeof moves.value;
        }
    });
});

onMounted(initialise);
onBeforeUnmount(() => {
    resetSubscriptions();
});
</script>
