// examples/react/react-pwa-app/src/App.tsx
import { useComponentValue } from "@dojoengine/react";
import { Entity } from "@dojoengine/recs";
import { useEffect, useState } from "react";
import { Direction } from "./utils";
import { getEntityIdFromKeys } from "@dojoengine/utils";
import { useDojo } from "./dojo/useDojo";
import "./App.css";

function App() {
    const {
        setup: {
            systemCalls: { spawn, move },
            clientComponents: { Position, Moves },
        },
        burnerManager: {
            applyFromClipboard,
            copyToClipboard,
            list,
            count,
            select,
            clear,
            account,
            isDeploying,
            create,
        },
    } = useDojo();

    const [clipboardStatus, setClipboardStatus] = useState({
        message: "",
        isError: false,
    });

    const [entityId, setEntityId] = useState<Entity | undefined>(undefined);

    const position = useComponentValue(Position, entityId);
    const moves = useComponentValue(Moves, entityId);

    useEffect(() => {
        if (account) {
            const newEntityId = getEntityIdFromKeys([
                BigInt(account.address),
            ]) as Entity;
            setEntityId(newEntityId);
        } else {
            setEntityId(undefined);
        }
    }, [account]);

    const handleRestoreBurners = async () => {
        try {
            await applyFromClipboard();
            setClipboardStatus({
                message: "Burners restored successfully!",
                isError: false,
            });
        } catch (error) {
            setClipboardStatus({
                message: `Failed to restore burners from clipboard`,
                isError: true,
            });
        }
    };

    useEffect(() => {
        if (clipboardStatus.message) {
            const timer = setTimeout(() => {
                setClipboardStatus({ message: "", isError: false });
            }, 3000);

            return () => clearTimeout(timer);
        }
    }, [clipboardStatus.message]);

    return (
        <>
            <button onClick={() => create()}>
                {isDeploying ? "deploying burner" : "create burner"}
            </button>
            {list().length > 0 && (
                <button onClick={async () => await copyToClipboard()}>
                    Save Burners to Clipboard
                </button>
            )}
            <button onClick={handleRestoreBurners}>
                Restore Burners from Clipboard
            </button>
            {clipboardStatus.message && (
                <div className={clipboardStatus.isError ? "error" : "success"}>
                    {clipboardStatus.message}
                </div>
            )}

            <div className="card">
                <div>{`burners deployed: ${count}`}</div>
                <div>
                    select signer:{" "}
                    <select
                        value={account ? account.address : ""}
                        onChange={(e) => select(e.target.value)}
                    >
                        {list().map((account, index) => {
                            return (
                                <option value={account.address} key={index}>
                                    {account.address}
                                </option>
                            );
                        })}
                    </select>
                </div>
                <div>
                    <button onClick={() => clear()}>Clear burners</button>
                </div>
            </div>

            {account && (
                <>
                    <p>
                        You will need to Authorise the contracts before you can
                        use a burner. See readme.
                    </p>
                    <div className="card">
                        <button onClick={() => spawn(account)}>Spawn</button>
                        <div>
                            Moves Left:{" "}
                            {moves ? `${moves.remaining}` : "Need to Spawn"}
                        </div>
                        <div>
                            Position:{" "}
                            {position
                                ? `${position.vec.x}, ${position.vec.y}`
                                : "Need to Spawn"}
                        </div>

                        <div>{moves && moves.last_direction}</div>
                    </div>

                    <div className="card">
                        <div>
                            <button
                                onClick={() =>
                                    position && position.vec.y > 0
                                        ? move(account, Direction.Up)
                                        : console.log(
                                              "Reach the borders of the world."
                                          )
                                }
                            >
                                Move Up
                            </button>
                        </div>
                        <div>
                            <button
                                onClick={() =>
                                    position && position.vec.x > 0
                                        ? move(account, Direction.Left)
                                        : console.log(
                                              "Reach the borders of the world."
                                          )
                                }
                            >
                                Move Left
                            </button>
                            <button
                                onClick={() => move(account, Direction.Right)}
                            >
                                Move Right
                            </button>
                        </div>
                        <div>
                            <button
                                onClick={() => move(account, Direction.Down)}
                            >
                                Move Down
                            </button>
                        </div>
                    </div>
                </>
            )}
        </>
    );
}

export default App;

// example/frameworks/svelte/src/App.svelte
<script lang="ts">
import type { Entity } from "@dojoengine/recs";
import { getEntityIdFromKeys } from "@dojoengine/utils";
import { DirectionValue } from "@showcase/dojo";

import {
    componentValueStore,
    type ComponentStore,
} from "./dojo/componentValueStore";
import {
    handleBurnerChange,
    handleClearBurners,
    handleNewBurner,
} from "./dojo/handlers";
import { accountStore, burnerStore, dojoStore } from "./dojo/stores";

let entityId: Entity | undefined;
let positionStore: ComponentStore | undefined;
let movesStore: ComponentStore | undefined;
let clipboardMessage = "";
let clipboardError = false;

$: setup = $dojoStore;
$: account = $accountStore;
$: burners = $burnerStore;

$: if (account) {
    entityId = getEntityIdFromKeys([BigInt(account.address)]) as Entity;
} else {
    entityId = undefined;
}

$: if (setup && entityId) {
    positionStore = componentValueStore(
        setup.clientComponents.Position,
        entityId
    );
    movesStore = componentValueStore(setup.clientComponents.Moves, entityId);
} else {
    positionStore = undefined;
    movesStore = undefined;
}

function showMessage(message: string, isError = false) {
    clipboardMessage = message;
    clipboardError = isError;
    setTimeout(() => {
        clipboardMessage = "";
        clipboardError = false;
    }, 2500);
}

async function copyBurners() {
    if (!setup) return;
    await setup.burnerManager.copyToClipboard();
    showMessage("Burners copied to clipboard");
}

async function restoreBurners() {
    if (!setup) return;
    try {
        await setup.burnerManager.applyFromClipboard();
        burnerStore.set(setup.burnerManager.list());
        accountStore.set(setup.burnerManager.getActiveAccount());
        showMessage("Burners restored");
    } catch (error) {
        console.error(error);
        showMessage("Failed to restore burners", true);
    }
}
</script>

<main>
    {#if !setup}
        <p>Connecting to dojo…</p>
    {:else}
        <section>
            <button on:click={handleNewBurner}>
                {setup.burnerManager.isDeploying
                    ? "Deploying burner"
                    : "Create burner"}
            </button>
            {#if burners.length > 0}
                <button on:click={copyBurners}>Save burners to clipboard</button>
            {/if}
            <button on:click={restoreBurners}>Restore burners from clipboard</button>
            {#if clipboardMessage}
                <p class="feedback" class:error={clipboardError}>
                    {clipboardMessage}
                </p>
            {/if}
        </section>

        <section>
            <p>{`Burners deployed: ${burners.length}`}</p>
            <label class="select">
                <span>Select signer</span>
                <select on:change={handleBurnerChange}>
                    {#each burners as burner}
                        <option
                            value={burner.address}
                            selected={account && burner.address === account.address}
                        >
                            {burner.address}
                        </option>
                    {/each}
                </select>
            </label>
            <button on:click={handleClearBurners}>Clear burners</button>
        </section>

        <section>
            <button
                on:click={() =>
                    account && setup.systemCalls.spawn(account)
                }
            >
                Spawn
            </button>
            <p>
                Moves left:
                {#if movesStore}
                    {$movesStore?.remaining}
                {:else}
                    Need to spawn
                {/if}
            </p>
            <p>
                Position:
                {#if positionStore}
                    {$positionStore?.vec.x}, {$positionStore?.vec.y}
                {:else}
                    Need to spawn
                {/if}
            </p>
        </section>

        <section>
            <button
                on:click={() =>
                    account && positionStore && $positionStore?.vec.y > 0
                        ? setup.systemCalls.move(account, DirectionValue.Up())
                        : null
                }
            >
                Up
            </button>
            <div class="row">
                <button
                    on:click={() =>
                        account && positionStore && $positionStore?.vec.x > 0
                            ? setup.systemCalls.move(account, DirectionValue.Left())
                            : null
                    }
                >
                    Left
                </button>
                <button
                    on:click={() =>
                        account && setup.systemCalls.move(account, DirectionValue.Right())
                    }
                >
                    Right
                </button>
            </div>
            <button
                on:click={() =>
                    account && setup.systemCalls.move(account, DirectionValue.Down())
                }
            >
                Down
            </button>
        </section>
    {/if}
</main>
