// example/frameworks/svelte/src/App.svelte
<script lang="ts">
import type { Entity } from "@dojoengine/recs";
import { getEntityIdFromKeys } from "@dojoengine/utils";
import { DirectionValue } from "@showcase/dojo";

import {
    componentValueStore,
    type ComponentStore,
} from "./dojo/componentValueStore";
import {
    handleBurnerChange,
    handleClearBurners,
    handleNewBurner,
} from "./dojo/handlers";
import { accountStore, burnerStore, dojoStore } from "./dojo/stores";

let entityId: Entity | undefined;
let positionStore: ComponentStore | undefined;
let movesStore: ComponentStore | undefined;
let clipboardMessage = "";
let clipboardError = false;

$: setup = $dojoStore;
$: account = $accountStore;
$: burners = $burnerStore;

$: if (account) {
    entityId = getEntityIdFromKeys([BigInt(account.address)]) as Entity;
} else {
    entityId = undefined;
}

$: if (setup && entityId) {
    positionStore = componentValueStore(
        setup.clientComponents.Position,
        entityId
    );
    movesStore = componentValueStore(setup.clientComponents.Moves, entityId);
} else {
    positionStore = undefined;
    movesStore = undefined;
}

function showMessage(message: string, isError = false) {
    clipboardMessage = message;
    clipboardError = isError;
    setTimeout(() => {
        clipboardMessage = "";
        clipboardError = false;
    }, 2500);
}

async function copyBurners() {
    if (!setup) return;
    await setup.burnerManager.copyToClipboard();
    showMessage("Burners copied to clipboard");
}

async function restoreBurners() {
    if (!setup) return;
    try {
        await setup.burnerManager.applyFromClipboard();
        burnerStore.set(setup.burnerManager.list());
        accountStore.set(setup.burnerManager.getActiveAccount());
        showMessage("Burners restored");
    } catch (error) {
        console.error(error);
        showMessage("Failed to restore burners", true);
    }
}
</script>

<main>
    {#if !setup}
        <p>Connecting to dojo…</p>
    {:else}
        <section>
            <button on:click={handleNewBurner}>
                {setup.burnerManager.isDeploying
                    ? "Deploying burner"
                    : "Create burner"}
            </button>
            {#if burners.length > 0}
                <button on:click={copyBurners}>Save burners to clipboard</button>
            {/if}
            <button on:click={restoreBurners}>Restore burners from clipboard</button>
            {#if clipboardMessage}
                <p class="feedback" class:error={clipboardError}>
                    {clipboardMessage}
                </p>
            {/if}
        </section>

        <section>
            <p>{`Burners deployed: ${burners.length}`}</p>
            <label class="select">
                <span>Select signer</span>
                <select on:change={handleBurnerChange}>
                    {#each burners as burner}
                        <option
                            value={burner.address}
                            selected={account && burner.address === account.address}
                        >
                            {burner.address}
                        </option>
                    {/each}
                </select>
            </label>
            <button on:click={handleClearBurners}>Clear burners</button>
        </section>

        <section>
            <button
                on:click={() =>
                    account && setup.systemCalls.spawn(account)
                }
            >
                Spawn
            </button>
            <p>
                Moves left:
                {#if movesStore}
                    {$movesStore?.remaining}
                {:else}
                    Need to spawn
                {/if}
            </p>
            <p>
                Position:
                {#if positionStore}
                    {$positionStore?.vec.x}, {$positionStore?.vec.y}
                {:else}
                    Need to spawn
                {/if}
            </p>
        </section>

        <section>
            <button
                on:click={() =>
                    account && positionStore && $positionStore?.vec.y > 0
                        ? setup.systemCalls.move(account, DirectionValue.Up())
                        : null
                }
            >
                Up
            </button>
            <div class="row">
                <button
                    on:click={() =>
                        account && positionStore && $positionStore?.vec.x > 0
                            ? setup.systemCalls.move(account, DirectionValue.Left())
                            : null
                    }
                >
                    Left
                </button>
                <button
                    on:click={() =>
                        account && setup.systemCalls.move(account, DirectionValue.Right())
                    }
                >
                    Right
                </button>
            </div>
            <button
                on:click={() =>
                    account && setup.systemCalls.move(account, DirectionValue.Down())
                }
            >
                Down
            </button>
        </section>
    {/if}
</main>

// example/frameworks/react/src/App.tsx
import { useComponentValue } from "@dojoengine/react";
import type { Entity } from "@dojoengine/recs";
import { useEffect, useState } from "react";

import { getEntityIdFromKeys } from "@dojoengine/utils";

import { useDojo } from "./dojo/useDojo";
import { DirectionValue } from "@showcase/dojo";

import "./app.css";

function App() {
    const {
        setup: {
            systemCalls: { spawn, move },
            clientComponents: { Position, Moves },
        },
        account,
    } = useDojo();

    const [clipboardStatus, setClipboardStatus] = useState({
        message: "",
        isError: false,
    });

    const entityId = getEntityIdFromKeys([
        BigInt(account?.account.address),
    ]) as Entity;

    const position = useComponentValue(Position, entityId);
    const moves = useComponentValue(Moves, entityId);

    const handleRestoreBurners = async () => {
        try {
            await account?.applyFromClipboard();
            setClipboardStatus({ message: "Burners restored", isError: false });
        } catch {
            setClipboardStatus({
                message: "Failed to restore burners",
                isError: true,
            });
        }
    };

    useEffect(() => {
        if (!clipboardStatus.message) return;
        const timer = setTimeout(() => {
            setClipboardStatus({ message: "", isError: false });
        }, 3000);
        return () => clearTimeout(timer);
    }, [clipboardStatus.message]);

    return (
        <main className="app">
            <section className="card">
                <button onClick={() => account?.create()}>
                    {account?.isDeploying
                        ? "Deploying burner"
                        : "Create burner"}
                </button>
                {account && account?.list().length > 0 && (
                    <button onClick={() => account?.copyToClipboard()}>
                        Save burners to clipboard
                    </button>
                )}
                <button onClick={handleRestoreBurners}>
                    Restore burners from clipboard
                </button>
                {clipboardStatus.message && (
                    <p
                        className={
                            clipboardStatus.isError ? "error" : "success"
                        }
                    >
                        {clipboardStatus.message}
                    </p>
                )}
            </section>

            <section className="card">
                <p>{`burners deployed: ${account.count}`}</p>
                <label className="select">
                    <span>Select signer</span>
                    <select
                        value={account ? account.account.address : ""}
                        onChange={(event) => account.select(event.target.value)}
                    >
                        {account?.list().map((burner, index) => (
                            <option value={burner.address} key={index}>
                                {burner.address}
                            </option>
                        ))}
                    </select>
                </label>
                <button onClick={() => account.clear()}>Clear burners</button>
            </section>

            <section className="card">
                <button onClick={() => spawn(account.account)}>Spawn</button>
                <p>
                    Moves left: {moves ? `${moves.remaining}` : "Need to spawn"}
                </p>
                <p>
                    Position:{" "}
                    {position
                        ? `${position.vec.x}, ${position.vec.y}`
                        : "Need to spawn"}
                </p>
            </section>

            <section className="card grid">
                <button
                    onClick={() =>
                        position && position.vec.y > 0
                            ? move(account.account, DirectionValue.Up())
                            : null
                    }
                >
                    Up
                </button>
                <div className="row">
                    <button
                        onClick={() =>
                            position && position.vec.x > 0
                                ? move(account.account, DirectionValue.Left())
                                : null
                        }
                    >
                        Left
                    </button>
                    <button
                        onClick={() =>
                            move(account.account, DirectionValue.Right())
                        }
                    >
                        Right
                    </button>
                </div>
                <button
                    onClick={() => move(account.account, DirectionValue.Down())}
                >
                    Down
                </button>
            </section>
        </main>
    );
}

export default App;
